### ISSUE TITLE
Node list from zone

### ISSUE THREAD

**Issue by muquang** [dyninc/dyn-php#12]
I want to get node list from selected zone. Any example to do it?

**Comment by tfountain** [comment]
Try this:

```php

use Dyn\TrafficManagement;

$tm = new TrafficManagement('customerName', 'username', 'password');
$tm->createSession();

$zone = $tm->getZone('example.com');
$records = $zone->getAllRecords();

var_dump($records);
```

That will give you an array of records on the zone, indexed by record type. E.g. `$records['A']` will contain all the 'A' records from the zone.

**Comment by muquang** [comment]
Thanks for your reply @tfountain
