### ISSUE TITLE
how does one set the timeout values for the api calls?

### ISSUE THREAD

**Issue by lfxc** [dyninc/dyn-php#17]
thanks!

**Comment by tfountain** [comment]
Hi @lfxc,

The optional 4th parameter to the `TrafficManagement` constructor allows you to provide an array of configuration values to the Zend HTTP client (which the SDK uses for the API calls). To specify a timeout of 30 seconds, that would be:

```
$tm = new TrafficManagement('customerName', 'username', 'password', array(
    'timeout' => 30
));
```

For email, it's the 2nd parameter instead:

```
$mm = new MessageManagement('APIKEY', array(
    'timeout' => 30
));
```

The default timeout is 300 seconds (5 minutes). 

Hope this helps,
Tim.

**Comment by lfxc** [comment]
perfect.  thanks!
