### ISSUE TITLE
TrafficManagement.php -> getZones()

### ISSUE THREAD

**Issue by brianmorton** [dyninc/dyn-php#18]
I could be missing something, but based on the example script I have modified it to try and fetch all zones but instead I get back an empty array.

```
<?php
use Dyn\TrafficManagement;
use Dyn\TrafficManagement\Record\A;

require ('./vendor/autoload.php');

$tm = new TrafficManagement('customer', 'user', 'password');

// login
$tm->createSession();

$allZones = $tm->getZones();

print_r($allZones[0]->getAllRecords());

exit;
```

Obviously I have omitted my credentials here, but if I use the same code for fetching a single zone it works fine.

**Comment by brianmorton** [comment]
I have since learned this is due to the hardcoded 5 second timeout on API calls. Since it just returns blank, I am having trouble getting the Job ID to poll for the status of this operation...

**Comment by brianmorton** [comment]
I have resolved this, although it took quite a bit of time to figure out the problems. Better explanations here and on the API docs about the 5 second time limit would be helpful.

**Comment by tfountain** [comment]
Hi @brianmorton,

Glad you found a solution for this. Could you give me a rough idea how many records you have in the zone you were testing, so I can give this a try myself and hopefully improve the functionality?

Thanks,
Tim.

**Comment by brianmorton** [comment]
@tfountain 
It seemed to respond fine (~3 seconds) when there were 340 records which was for the second client I tested.

The first client had over 1000 primary zones, which I imagine (based on the ~3s for 340) would have taken 10+ seconds.

The solution/troubleshooting (for any potential readers who may also have this problem) was to pass in a Zend HttpClient to create the TrafficManagement session and then use something like `getLastResponse()` when there was a falsey return to see what was really happening.
