### ISSUE TITLE
Requests too close together

### ISSUE THREAD

**Issue by fogeytron** [dyninc/dyn-php#2]
Hi,

After I create a zone, I then immediately create a record for that zone, 90% of the time the record does not get created.

I added a additional line of code sleep(5) between the calls in my code, and that seems to work, this is not ideal though.

Looking over the sdk, I noticed that if any of the api calls fail, the sdk simply returns false, so i am never able to retrieve the error message from the sdk to determine what the error message is.

Also when creating a zone, the same issue arises, it returns false on failure.

I know that the system uses jobs, that is why it always returns a job id in the response, but I did not see the ability to get a job using the sdk.

If you could help me out, that would be great.

Thanks.

**Comment by tfountain** [comment]
I'm going to close this. Please let us know if you're still having issues.
